seaport/config/routes.rb
Rails.application.routes.draw do
  resources :ships
  resources :docks
  resources :ports
  resources :insurances
  resources :cargos
  resources :companies
  root to: 'pages#dashboard'
  get 'pages/dashboard'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

seaport/app/models/cargo.rb
class Cargo < ApplicationRecord
end

seaport/app/controllers/cargos_controller.rb
class CargosController < ApplicationController
  before_action :set_cargo, only: [:show, :edit, :update, :destroy]

  # GET /cargos
  # GET /cargos.json
  def index
    @cargos = Cargo.all
  end

  # GET /cargos/1
  # GET /cargos/1.json
  def show
  end

  # GET /cargos/new
  def new
    @cargo = Cargo.new
  end

  # GET /cargos/1/edit
  def edit
  end

  # POST /cargos
  # POST /cargos.json
  def create
    @cargo = Cargo.new(cargo_params)

    respond_to do |format|
      if @cargo.save
        format.html { redirect_to @cargo, notice: 'Cargo was successfully created.' }
        format.json { render :show, status: :created, location: @cargo }
      else
        format.html { render :new }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cargos/1
  # PATCH/PUT /cargos/1.json
  def update
    respond_to do |format|
      if @cargo.update(cargo_params)
        format.html { redirect_to @cargo, notice: 'Cargo was successfully updated.' }
        format.json { render :show, status: :ok, location: @cargo }
      else
        format.html { render :edit }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cargos/1
  # DELETE /cargos/1.json
  def destroy
    @cargo.destroy
    respond_to do |format|
      format.html { redirect_to cargos_url, notice: 'Cargo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cargo
      @cargo = Cargo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cargo_params
      params.require(:cargo).permit(:selling_company_id, :buying_company_id, :container_number, :container_value, :goods)
    end
end

seaport/app/helpers/cargos_helper.rb
module CargosHelper
end

seaport/app/views/cargos/_form.html.erb
<%= form_with(model: cargo, local: true) do |form| %>
  <% if cargo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cargo.errors.count, "error") %> prohibited this cargo from being saved:</h2>

      <ul>
        <% cargo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :selling_company_id %>
    <%= form.number_field :selling_company_id %>
  </div>

  <div class="field">
    <%= form.label :buying_company_id %>
    <%= form.number_field :buying_company_id %>
  </div>

  <div class="field">
    <%= form.label :container_number %>
    <%= form.text_field :container_number %>
  </div>

  <div class="field">
    <%= form.label :container_value %>
    <%= form.number_field :container_value %>
  </div>

  <div class="field">
    <%= form.label :goods %>
    <%= form.text_field :goods %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

seaport/app/views/cargos/edit.html.erb
<h1>Editing Cargo</h1>

<%= render 'form', cargo: @cargo %>

<%= link_to 'Show', @cargo %> |
<%= link_to 'Back', cargos_path %>

seaport/app/views/cargos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cargos</h1>

<table>
  <thead>
    <tr>
      <th>Selling company</th>
      <th>Buying company</th>
      <th>Container number</th>
      <th>Container value</th>
      <th>Goods</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cargos.each do |cargo| %>
      <tr>
        <td><%= cargo.selling_company_id %></td>
        <td><%= cargo.buying_company_id %></td>
        <td><%= cargo.container_number %></td>
        <td><%= cargo.container_value %></td>
        <td><%= cargo.goods %></td>
        <td><%= link_to 'Show', cargo %></td>
        <td><%= link_to 'Edit', edit_cargo_path(cargo) %></td>
        <td><%= link_to 'Destroy', cargo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cargo', new_cargo_path %>

seaport/app/views/cargos/new.html.erb
<h1>New Cargo</h1>

<%= render 'form', cargo: @cargo %>

<%= link_to 'Back', cargos_path %>

seaport/app/views/cargos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Selling company:</strong>
  <%= @cargo.selling_company_id %>
</p>

<p>
  <strong>Buying company:</strong>
  <%= @cargo.buying_company_id %>
</p>

<p>
  <strong>Container number:</strong>
  <%= @cargo.container_number %>
</p>

<p>
  <strong>Container value:</strong>
  <%= @cargo.container_value %>
</p>

<p>
  <strong>Goods:</strong>
  <%= @cargo.goods %>
</p>

<%= link_to 'Edit', edit_cargo_path(@cargo) %> |
<%= link_to 'Back', cargos_path %>