seaport/config/routes.rb
Rails.application.routes.draw do
  resources :ships
  resources :docks
  resources :ports
  resources :insurances
  resources :cargos
  resources :companies
  root to: 'pages#dashboard'
  get 'pages/dashboard'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

seaport/app/models/insurance.rb
class Insurance < ApplicationRecord
  belongs_to :company

  def ship
    Ship.first
  end
end

seaport/app/controllers/insurances_controller.rb
class InsurancesController < ApplicationController
  before_action :set_insurance, only: [:show, :edit, :update, :destroy]

  # GET /insurances
  # GET /insurances.json
  def index
    @insurances = Insurance.all
  end

  # GET /insurances/1
  # GET /insurances/1.json
  def show
  end

  # GET /insurances/new
  def new
    @insurance = Insurance.new
  end

  # GET /insurances/1/edit
  def edit
  end

  # POST /insurances
  # POST /insurances.json
  def create
    @insurance = Insurance.new(insurance_params)

    respond_to do |format|
      if @insurance.save
        format.html { redirect_to @insurance, notice: 'Insurance was successfully created.' }
        format.json { render :show, status: :created, location: @insurance }
      else
        format.html { render :new }
        format.json { render json: @insurance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insurances/1
  # PATCH/PUT /insurances/1.json
  def update
    respond_to do |format|
      if @insurance.update(insurance_params)
        format.html { redirect_to @insurance, notice: 'Insurance was successfully updated.' }
        format.json { render :show, status: :ok, location: @insurance }
      else
        format.html { render :edit }
        format.json { render json: @insurance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insurances/1
  # DELETE /insurances/1.json
  def destroy
    @insurance.destroy
    respond_to do |format|
      format.html { redirect_to insurances_url, notice: 'Insurance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insurance
      @insurance = Insurance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def insurance_params
      params.require(:insurance).permit(:company_id, :insurance_type, :premium, :insurance_number, :cargo)
    end
end

seaport/app/helpers/insurances_helper.rb
module InsurancesHelper
end

seaport/app/views/insurances/_form.html.erb
<%= bootstrap_form_for(insurance, local: true, layout: :horizontal) do |form| %>
  <% if insurance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(insurance.errors.count, "error") %> prohibited this insurance from being saved:</h2>

      <ul>
        <% insurance.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.collection_select :ship, Ship.all, :id, :name %>

  <%= form.text_field :insurance_type, label: 'Type of Insurance' %>

  <%= form.number_field :premium, label: 'Premium Amount (in ₹)' %>

  <%= form.text_field :cargo_id, label: 'Type of Cargo associated with Ship' %>

  <%= form.file_field :document, value: nil, label: 'Upload Reciept' %>

  <div class="text-center">
    <%= form.submit 'Register Insurance', class: 'btn btn-primary' %>
  </div>
<% end %>

seaport/app/views/insurances/edit.html.erb
<h1>Editing Insurance</h1>

<%= render 'form', insurance: @insurance %>

<%= link_to 'Show', @insurance %> |
<%= link_to 'Back', insurances_path %>

seaport/app/views/insurances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Insurances</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Insurance type</th>
      <th>Premium</th>
      <th>Insurance number</th>
      <th>Cargo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @insurances.each do |insurance| %>
      <tr>
        <td><%= insurance.company_id %></td>
        <td><%= insurance.insurance_type %></td>
        <td><%= insurance.premium %></td>
        <td><%= insurance.insurance_number %></td>
        <td><%= insurance.cargo %></td>
        <td><%= link_to 'Show', insurance %></td>
        <td><%= link_to 'Edit', edit_insurance_path(insurance) %></td>
        <td><%= link_to 'Destroy', insurance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Insurance', new_insurance_path %>

seaport/app/views/insurances/new.html.erb
<%= content_for :title do %>Register Insurance<% end %>

<div class="row">
  <div class="col-lg-12">
    <div class="card shadow mb-4">
      <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">
          Register Insurance
        </h6>
      </div>

      <div class="card-body">
        <%= render 'form', insurance: @insurance %>
      </div>
    </div>
  </div>
</div>

seaport/app/views/insurances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @insurance.company_id %>
</p>

<p>
  <strong>Insurance type:</strong>
  <%= @insurance.insurance_type %>
</p>

<p>
  <strong>Premium:</strong>
  <%= @insurance.premium %>
</p>

<p>
  <strong>Insurance number:</strong>
  <%= @insurance.insurance_number %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @insurance.cargo %>
</p>

<%= link_to 'Edit', edit_insurance_path(@insurance) %> |
<%= link_to 'Back', insurances_path %>