seaport/config/routes.rb
Rails.application.routes.draw do
  resources :ships
  resources :docks
  resources :ports
  resources :insurances
  resources :cargos
  resources :companies
  root to: 'pages#dashboard'
  get 'pages/dashboard'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

seaport/app/models/port.rb
class Port < ApplicationRecord
end

seaport/app/controllers/ports_controller.rb
class PortsController < ApplicationController
  before_action :set_port, only: [:show, :edit, :update, :destroy]

  # GET /ports
  # GET /ports.json
  def index
    @ports = Port.all
  end

  # GET /ports/1
  # GET /ports/1.json
  def show
  end

  # GET /ports/new
  def new
    @port = Port.new
  end

  # GET /ports/1/edit
  def edit
  end

  # POST /ports
  # POST /ports.json
  def create
    @port = Port.new(port_params)

    respond_to do |format|
      if @port.save
        format.html { redirect_to @port, notice: 'Port was successfully created.' }
        format.json { render :show, status: :created, location: @port }
      else
        format.html { render :new }
        format.json { render json: @port.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ports/1
  # PATCH/PUT /ports/1.json
  def update
    respond_to do |format|
      if @port.update(port_params)
        format.html { redirect_to @port, notice: 'Port was successfully updated.' }
        format.json { render :show, status: :ok, location: @port }
      else
        format.html { render :edit }
        format.json { render json: @port.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ports/1
  # DELETE /ports/1.json
  def destroy
    @port.destroy
    respond_to do |format|
      format.html { redirect_to ports_url, notice: 'Port was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_port
      @port = Port.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def port_params
      params.require(:port).permit(:name, :license, :address, :phone_number)
    end
end

seaport/app/helpers/ports_helper.rb
module PortsHelper
end

seaport/app/views/ports/_form.html.erb
<%= form_with(model: port, local: true) do |form| %>
  <% if port.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(port.errors.count, "error") %> prohibited this port from being saved:</h2>

      <ul>
        <% port.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :license %>
    <%= form.text_field :license %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

seaport/app/views/ports/edit.html.erb
<h1>Editing Port</h1>

<%= render 'form', port: @port %>

<%= link_to 'Show', @port %> |
<%= link_to 'Back', ports_path %>

seaport/app/views/ports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ports</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>License</th>
      <th>Address</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ports.each do |port| %>
      <tr>
        <td><%= port.name %></td>
        <td><%= port.license %></td>
        <td><%= port.address %></td>
        <td><%= port.phone_number %></td>
        <td><%= link_to 'Show', port %></td>
        <td><%= link_to 'Edit', edit_port_path(port) %></td>
        <td><%= link_to 'Destroy', port, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Port', new_port_path %>

seaport/app/views/ports/new.html.erb
<h1>New Port</h1>

<%= render 'form', port: @port %>

<%= link_to 'Back', ports_path %>

seaport/app/views/ports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @port.name %>
</p>

<p>
  <strong>License:</strong>
  <%= @port.license %>
</p>

<p>
  <strong>Address:</strong>
  <%= @port.address %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @port.phone_number %>
</p>

<%= link_to 'Edit', edit_port_path(@port) %> |
<%= link_to 'Back', ports_path %>